### PR TITLE
FEAT: Update ScummVM Standalone to 2.9.0git

### PR DESCRIPTION
**Pull request by XK9274**
## Overview
Update to scummvm 2.9.0 to include all updates & fixes to the scrollbars in: https://github.com/scummvm/scummvm/pull/5472

Run ScummVM_000Run ScummVM_001

## To test

Testing GUI -> 640 x 480: 

- [x]  GUI can be freely scaled to its smallest size

Testing scrollbars:

- [x]  Open global options -> Keymaps & observe a scrollbar is still present

Downscaler can be tested by running BSword2.5. 
Audio has been handled differently so in this PR will also change the launch scripts to preload libpadsp.so

## Build details
<details>

```markdown
Backend... miyoo (SDL 1.2.15), 16bit color, high resolution, TinyGL, savegame timestamp, HQ and Edge scalers, aspect ratio correction, Lua, virtual keyboard, ENet
WARNING: Disabling engine Hpl1 because the following dependencies are unmet: OpenGL with shaders
WARNING: Disabling engine Tetraedge because the following dependencies are unmet: libtheoradec
WARNING: Disabling engine The Watchmaker because the following dependencies are unmet: OpenGL (classic)

Engines (builtin):
    SCUMM [all games]
    Access
    ADL
    AGI
    AGOS [all games]
    Adventure Game Studio
    Sanitarium
    Lord Avalot d'Argent
    Beavis and Butthead in Virtual Stupidity
    Blade Runner
    The Journeyman Project 2: Buried in Time
    CGE
    CGE2
    Chamber
    Chewy: Esc from F5
    Cinematique evo 1
    Magic Composer
    Crab
    Cinematique evo 2
    Lost Eden
    Cryo Omni3D games [all games]
    Macromedia Director
    Dungeon Master
    Dragon History
    Blazing Dragons
    Drascula: The Vampire Strikes Back
    Dreamweb
    Escape From Hell
    Freescape
    Glk Interactive Fiction games
    UFOs
    Gobli*ns
    The Griffon Legend
    Grim [all games]
    Groovie [all games]
    Hades Challenge
    Hyperspace Delivery Boy!
    Hopkins FBI
    Hugo Trilogy
    Hypnotix Inc.
    In Cold Blood
    Illusions Engine
    The Immortal
    Kingdom: The Far Reaches
    Kyra [all games]
    Labyrinth of Time
    The Last Express
    Lilliput
    Lure of the Temptress
    MacVenture
    MADE
    MADS [all games]
    Might and Magic [all games]
    Mohawk [all games]
    Mortevielle
    mTropolis
    Mutation of JB
    Myst 3
    Nancy Drew
    Neverhood
    Nikita Game Interface
    Parallaction
    The Journeyman Project: Pegasus Prime
    Red Comrades
    Pink Panther
    Playground 3d: the testing and playground environment for 3d renderers
    Plumbers Don't Wear Ties
    The Prince and The Coward
    Private Eye
    Flight of the Amazon Queen
    SAGA [all games]
    SAGA2
    SCI [all games]
    The Lost Files of Sherlock Holmes
    Beneath a Steel Sky
    Sludge
    The Longest Journey
    Star Trek 25th Anniversary/Judgment Rites
    Mission Supernova
    Broken Sword
    Broken Sword II
    Broken Sword 2.5
    Teen Agent
    TestBed: the Testing framework
    Tinsel
    Starship Titanic
    3 Skulls of the Toltecs
    Tony Tough and the Night of Roasted Moths
    Toonstruck
    Touche: The Adventures of the Fifth Musketeer
    Trecision Adventure Module
    TsAGE
    Bud Tucker in Double Trouble
    Little Big Adventure
    Ultima [all games]
    V-Cruise
    Voyeur
    WAGE
    Wintermute [all games]
    Z-Vision

Engines Skipped:
    Hpl1
    Tetraedge
    The Watchmaker

WARNING: This ScummVM build contains the following UNSTABLE engines:
    Lord Avalot d'Argent
    Chamber
    Crab
    Lost Eden
    Dungeon Master
    Grim [Escape from Monkey Island]
    In Cold Blood
    The Immortal
    The Last Express
    Lilliput
    MacVenture
    MADS [MADS V2]
    Might and Magic
    Mohawk [Where in Time is Carmen Sandiego?]
    Mutation of JB
    Playground 3d: the testing and playground environment for 3d renderers
    Sludge
    Star Trek 25th Anniversary/Judgment Rites
    TestBed: the Testing framework
    Ultima [Ultima I - The First Age of Darkness]
    WAGE
    Wintermute [Wintermute3D]

Creating engines/engines.mk
Creating engines/detection_table.h
Creating engines/plugins_table.h
Creating config.h
Creating config.mk

```
</details>

### CODE REVIEW

**Comment by Leemann07** [comment]
Thank you very much !!!!

**Review by schmurtzm — APPROVED** [review]
Work very well.

**Comment by Leemann07** [comment]
Could i know if this has been applied to Update ScummVM Standalone to 2.9.0git #1307 ?
https://github.com/scummvm/scummvm/pull/5504

**Comment by XK9274** [comment]
No, ScummVM in the PR was built December 5th

**Comment by Leemann07** [comment]
Ok I'll wait for the next update :)  Thank you for your scummvm Miyoo mini standalone build!
you are best

**Comment by Leemann07** [comment]
hello. I have a question. Can you tell me what toolchain I should use to build scummvm for Miyoo mini Onion like you do? Please advise on this. I built it last time but it wasn‘t successful. I learned how to use GitHub and Build for the first time this month and am eager to learn more! :) Bestregards Leemann

**Comment by XK9274** [comment]
> hello. I have a question. If you want could you tell me which toolchain I should use to build scummvm for Miyoo mini Onion like you do? Please advise on this. I built it last time but it wasn‘t successful. I learned how to use GitHub and Build for the first time this month and am eager to learn more! :) Bestregards Leemann

Hello, 

The toolchain i use is Shaun Inmans union toolchain - it doesn't include autotools though. 

You can run it with:

```
git clone https://github.com/shauninman/union-miyoomini-toolchain.git
cd union-miyoomini-toolchain
make shell
```

**Comment by Leemann07** [comment]
> > hello. I have a question. If you want could you tell me which toolchain I should use to build scummvm for Miyoo mini Onion like you do? Please advise on this. I built it last time but it wasn‘t successful. I learned how to use GitHub and Build for the first time this month and am eager to learn more! :) Bestregards Leemann
> 
> Hello,
> 
> The toolchain i use is Shaun Inmans union toolchain - it doesn't include autotools though.
> 
> You can run it with:
> 
> ```
> git clone https://github.com/shauninman/union-miyoomini-toolchain.git
> cd union-miyoomini-toolchain
> make shell
> ```
Thank you so much for your reply

I download scummvm from github on my MacBook and put it in the Shaun Inmans union toolchain - workspace.

  ./backends/platform/sdl/miyoo/build_miyoomini.sh
I have built several times using this. However, the scummvm Unix file is only 18.1MB in size and is lacking something.

I'm curious as to what part I built was wrong. 

Bsetregards Leemann

**Comment by Leemann07** [comment]
Could i know if this has been applied to Update ScummVM Standalone to 2.9.0git https://github.com/OnionUI/Onion/pull/1307 ?
https://github.com/scummvm/scummvm/pull/5504
https://github.com/scummvm/scummvm/pull/5507
https://github.com/scummvm/scummvm/pull/5505

**Comment by Leemann07** [comment]
I have a question, is it possible to build ScummVM to support sdl2 (opengl)?

**Pull request merged**
