### PR TITLE
GameSwitcher save/load feature

### PR DESCRIPTION
**Pull request by worthis**
### Overview
Modification of the original game switcher with the addition of save and load game state functionality.

### Adds
Menu items to Tweaks -> Advanced -> GameSwitcher...
- Enable save/load feature
- Max save states (from 5 to 25)
- Reset config (reset all gameswitcher configs)

### GameSwitcher controls with enabled save/load feature
Up/Down buttons - select the available save slot.
Buttons A and B depending on the selected save slot:
A - load the selected slot (if a numbered slot is selected, the current autosave slot will be replaced by the selected one),
B - save the current autoslot as a permanent one with the last free number, or delete the selected numbered slot.
MENU, X, Y, START and SELECT buttons - as usual.

_Note: The backlight brightness adjustment function will be replaced by save/load controls._

[GameSwitcherTweak.zip](https://github.com/OnionUI/Onion/files/12731551/GameSwitcherTweak.zip)

Tweaks_000
Tweaks_001

### CODE REVIEW

**Comment by tGecko** [comment]
Hey, can you maybe add some screenshots so we can see what this is about?

**Comment by worthis** [comment]
> Hey, can you maybe add some screenshots so we can see what this is about?
I made a short video [https://youtu.be/v4ClSGnKxv8](url)

**Comment by Aemiii91** [comment]
To me, it doesn't make much sense to include a "mod" in the project itself. Mods are inherently third-party stuff. This should be a tweak or a setting *inside* GameSwitcher.

**Comment by Aemiii91** [comment]
Hey, this is looking great. You're very welcome to join us over [on Discord](https://onionui.github.io/docs/dev/contribute), maybe we could discuss your ideas further ?

**Comment by worthis** [comment]
> Hey, this is looking great. You're very welcome to join us over [on Discord](https://onionui.github.io/docs/dev/contribute), maybe we could discuss your ideas further ?

Thank you.
I'm joined to the discord server.

**Comment by Aemiii91** [comment]
Very nice. Please introduce yourself in the [dev thread](https://discord.com/channels/529983248114122762/1007796369785897090) :)

**Comment by worthis** [comment]
Closed due to revised functionality - #1231.

**Pull request closed without merging**
