### PR TITLE
FIX: Remove the background from the wifi icon in MainUI

### PR DESCRIPTION
**Pull request by tGecko**
MainUI draws a red rectangle / the background of the theme / the title bar behind the WiFi icon.

Removing this allows for custom wifi icons that are offset from the usual WiFi icon position without having said background overlap the battery percentage.

Before
MainUI_002
After
MainUI_001

### CODE REVIEW

**Comment by XK9274** [comment]
it verrrks!

https://github.com/OnionUI/Onion/assets/47260768/a5b29cbe-a2a7-47ea-bdba-b968ed7c07b0

**Review by XK9274 — APPROVED** [review]

**Comment by becket33** [comment]
it verrrks! I cant believe it! And they said that imitation diamond wasn't good enough! :)

**Comment by TooGeekCreations** [comment]
XK9274 where can i find this screen recorder?

**Comment by XK9274** [comment]
> XK9274 where can i find this screen recorder?

https://github.com/XK9274/screencap-toolkit-miyoo

**Pull request merged**
