### PR TITLE
FIX: Trigger RetroArch related updates for users on 4.2-RC

### PR DESCRIPTION
**Pull request by Aemiii91**
The `RA_SUBVERSION` needed to be incremented, to trigger the update of RetroArch cores and settings.

### CODE REVIEW

**Comment by garpunkal** [comment]
just the 4.2.0 release? or create a release for it?

**Comment by Aemiii91** [comment]
Yes, you just need to delete the file and reinstall 4.2.0

**Comment by garpunkal** [comment]
done that, is there a way I can confirm it worked?

**Comment by Aemiii91** [comment]
The installer would've said 2/2 Updating RetroArch... and you should have the version file again

**Comment by garpunkal** [comment]
yep, file there with version: 1.15.0.5
I saw the updating RetroArch too.

**Comment by garpunkal** [comment]
thanks :)

**Pull request merged**
