### PR TITLE
FEAT: Netplay GLO menu

### PR DESCRIPTION
**Pull request by schmurtzm**
-  Implement centralized menu for "Netplay Standard", "Easy Netplay" and "Easy Netplay - Pokemon Trading" (For "Standard Netplay", join must be done manually from Retroarch menu).
- This new GLO script launcher should fix many Netplay crashs.
- `netplay_override.cfg` now reference a selection of cores dedicated to Netplay.
- `netplay_override.cfg` support overclock settings per core.
- Remove "Easy Netplay" and "pokemon trading" from apps : its now always available for MMP 
- Netplay game thumbnail are displayed before joining
- Automatic  GB / tgbdual configuration
- Automatic MD / picodrive configuration

**Under the hood :**
 - It select automatically the recommend core from the Netplay compatibility list ($sysdir/config/netplay_cores.conf)
    In this file a system is defined by its rom folder. If the corresponding core is set to "none" then the platform is considered as not compatible with Netplay.
 - Then it patches the Retroarch configuration (using "--appendconfig") as workaround for the following bugs  :
       - libretro/RetroArch#15248
       - libretro/RetroArch#15313
       - (This one could impact Netplay too, for reminder : libretro/RetroArch#15580)

You can now add overclock parameter by core in netplay_cores.conf.

- netplay_cores.cfg is now a csv with this structure : `Rom_Folder_Name;Core_Filename;Core_Config_Folder;CPUspeed;`
- Overclock is done by generating a cpuclock.txt in the core config folder. When quitting RA it restore the original cpu speed (or delete cpuclock.txt if there was nothing specifically configured)

 **Easy Netplay join improvements**

New scripts : hotspot_create.sh,  hotspot_join.sh and hotspot_cleanup.sh
	- Can be launched independantly from GLO
	- Allow to quit during easy netplay join script process
	- Wifi configuration is not modified in NAND anymore to join hotspot, $sysdir/config/hotspot_wpa_supplicant.conf will be used instead (allows to keep wifi working on unexpected reboot)

New `sync_file` function :
	- Now use xcrc instead of chksum binary
	- More generic "sync_file" function (used for cookie, core, img…) can skip or compare the file size, compare the checksum, ask for backup before replacing,…(examples detailed in the beginning of the function).
	- Post copy crc is now done to check if the copy is really OK
	- New internal logic for example if a core already exist but is different then the one from the server will be copied and used from ".netplay" subdirectory. It allows to maximize the chances to have Netplay working without altering the current user configuraiton. The ".netplay" subdirectory will only be used if the core is different from the server. This function should manage every cases (the file to sync doesn't not exist, the file exist but is different, the file exist and is identical).

Netplay.sh main GLO script now contains "`cores_configurator`" function to check cores configuration on the fly. GB/GBC and MD configurations are now fixed for Netplay on the fly if necessary.

 **Pokemon Trade scripts updates**

- Now use new `sync_file` function (manage if tgb dual versions are different)
- On "`confirm_join_panel`"
		- indicate who is host and clientdisplayer
		- Show box covers
- Sync box covers
- Use the new hotspot scripts (allow to quit during easy netplay join script process)
- Benefit from the automatic TGB Dual configuration
- Auto import saves from Gambatte
- Put a date on the save backup filename (allow to have multiple versions of the backup)

**Other fixes :** 
- "`--appendconfig=./.retroarch/netplay_override.cfg`" added to all Easy Netplay scripts  : should avoid some crash when navigating in RA menus to join a game for example
- TGB Dual display screen 1 and sound #1 by default when launched without Netplay
- "game_list_options.sh" has been updated to manage dynamic labels, it also allows to not show some GLO option when necessary. Thanks to these dynamic labels, GLO will indicate if the current platform is compatible or not with Netplay and will also display the current Netplay core recommended.
- All the scripts related to Netplay feature are now in `.tmp_update\script\netplay`.
- `prompt` app updated to avoid crash on empty option 
- `pressMenu2Kill` app updated to use pkill command (it allows easier string match to kill the desired task)
- Easy Netplay server now use netplay_cores.cfg to choose the right core and apply cpuclock if required
- The Easy Netplay client will inherit of the server cpuclock speed
- Create custom override config file for all Easy Netplay modes to improve the exit time (RA is not trying anymore to declare the server publicly and to open upnp ports)
- better management of FTP url for Easy Netplay
- fix Genesis / Mega Drive configuration

We are still looking for Netplay testers to fill the "Onion - Netplay" table and then be able to select the best Netplay cores for everyone in netplay_cores.cfg :
https://docs.google.com/spreadsheets/d/1y1esG3HcNagPG8cy-ulZK_mhhUb93pqG5_XEtRRgKQ4/edit?usp=sharing

**Demo :** 

https://github.com/OnionUI/Onion/assets/7110113/d794041c-babb-481a-b85e-2ac361bb20b0

### CODE REVIEW

**Comment by XK9274** [comment]
All tested on sub 5 minute sessions, some breaks/reboots inbetween 

- [x] pressmenu2kill working 

## Standard netplay:
- [x] Easy Netplay host/joining/file syncing with Balloon kid  - TGB dual
- [x] Auto core selection 
- [x] Player control/screen control on TGB Dual working as expected
- [x] Joined through RA GUI/SB/RA PC all OK. 

## Easy netplay:
- [x] Easy Netplay host/joining/file syncing with Balloon kid  - TGB dual
- [x] Auto core selection 
- [x] Player control/screen control on TGB Dual working as expected
- [x] Client cleanup and reassociation with original wifi on client
- [x] Client cleanup and reassociation with original wifi on host

## Easy netplay pokemon/cable link subsys (save stored in TGB Dual folder)
- [x] Easy Netplay host/joining/file syncing with Red on host Blue on client
- [x] Auto core selection 
- [x] Player control/screen control on TGB Dual working as expected
- [x] Save files transferred and managed
- [x] Full trade complete
- [x] Save files returned and loads fine after reload of RA.
- [x] Client cleanup and reassociation with original wifi on client
- [x] Client cleanup and reassociation with original wifi on host

## Easy netplay pokemon/cable link subsys (save stored in Gambatte folder)
- [x] Easy Netplay host/joining/file syncing with Red on host Blue on client
- [x] Player control/screen control on TGB Dual working as expected
- [x] Save files transferred and managed
- [x] Full trade complete
- [ ] ~~Save files returned and loads fine after reload of RA~~. - Does the save get moved back into the Gambette folder? (it's saved in TGB)

- Steps to reproduce
    - Delete all TGB dual saves/move saves to Gambatte folder
    - Start/complete a trade
    - In game menu -> Reset
    - Load in / save game
    - Retroarch menu -> quit
    - Wait for save sync
    - Restart game with Gambatte as core - either loads a save state or a previous save where the trade hadn't been completed
- Manual steps to fix
    - Copy saves from TGB dual folder to Gambatte folder
    - Reset game through GLO

- [x] Client cleanup and reassociation with original wifi on client
- [x] Client cleanup and reassociation with original wifi on host

I toyed with the idea of date as the backup indicator but without NTP they were busted anyway.. (The date will start at 1970 every time you reboot the device if you have emu time skip off (or NTP enabled but no access to wifi), so subsequent plays may result in saves that appear older than a previous backup, but infact they're the newer one) - this is why there was only ever 1 backup. 

Maybe we should look towards a "Save manager" app in the future?

**Comment by schmurtzm** [comment]
I have kept the backup save with date because it requires to have NTP disabled (which is strange for a pokemon user) then it requires to disable time skip (which is not by default and is a strange choice for someone who doesn't enable NTP) and after that to lost data it requires that the user make a save at the same precise second after booting.  Globally having the date will be probably the best choice to easily retrieve an old save.

For Pokemon trading, I have added the gambatte save restore and a way to avoid problems when the client is joining before the host has started.
- When the save is coming from Gambatte (= TGB Dual save not found) then the updated save after trading is restored in Gambatte (a backup of the save has been done previously)
- New feature : wait until the host has launched retroarch instead of notifying the user to respect a specific launch order (which means that once the client has started to join, the host has 25 seconds to launch the game) .

I still have a route problem when you invert the roles of each MMP (host/client) without restarting, I would be happy to have  your opinion on the subject 😉

**Review by XK9274 — APPROVED** [review]
Last version working fine, tests same as before but focused on ENP. 

Important note for any issues: 

Once you've done a trade you need to go into GLO and RESET GAME. (So it loads the srm, not the state)

**Comment by schmurtzm** [comment]
Update pushed : 
- Create "TGB Dual" save folder if it doesn't exist
- Rename the current save state after a successful save override from a trade. 

for Example : 
`Pokemon - Blue Version (USA, Europe) (SGB Enhanced).state.auto_20230920_020620`

It will avoid to have to explain to the user that he has to reset the game (which is a little hard to understand in this case). So now at the next launch the user should see the result of his trade without any additional manipulations.

**Review by Aemiii91 — APPROVED** [review]

**Pull request merged**
