### PR TITLE
FEAT: Add `smbd` to Tweaks for Samba file sync

### PR DESCRIPTION
**Pull request by XK9274**
# Samba 
Allows for the use of networked folder access.

## Features/additions:
- Samba related files & libraries
- Pre-set folder paths to Roms/Saves/SD Root & Screenshots. (More can be added in .tmp_update/config/smb.conf)

## Issues

~~Currently only works correctly if the call to start it comes from runtime.sh. There seems to be an environment/permissions issue which causes smbd to run but not allow access into subdirectories.~~  ~ Confirmed fixed.
https://github.com/OnionUI/Onion/pull/973#issuecomment-1627859106

## TO-DO

- [x] Do not share `rootSD` by default
- [x] Implement `shares` toggles in Tweaks (possibly dynamically from the contents of `smb.conf`)

## Test process

- [ ] Boot up with samba disabled
- [ ] Go to tweaks, network, enable Samba with the master toggle (using default config)
- [ ] Browse to the network share (windows: \\\x.x.x.x\ in explorer window, where x is the IP of the MMP)
- [ ] Check you have root directory access
- [ ] Check you can transfer a file to any of the folders, verify the file exists on the MMP with a `ls`
- [ ] Check files are visible from windows when a `touch` command is made
- [ ] Make a change to the file on windows, `cat` the file on the MMP - make sure changes synchronise
- [ ] Rename the file, make sure the change propagates across
- [ ] Check you have subdirectory access (EG, open Roms, open a folder that has Roms in it, make sure they're visible)
- [ ] Go down into the Samba submenu
- [ ] Disable some shares & refresh your explorer window when in the root location - observe the folders are removed
- [ ] Enable the shares & refresh your explorer window when in the root location - observe the folders are restored
- [ ] Disable wifi, return to tweaks - observe samba is disabled
- [ ] Enable wifi, return to tweaks, enable samba - observe samba is enabled and directory access restored

## Media

<table><td>

Tweaks_016

</td><td>

Tweaks_002

</td></table>
<table><td>

image

</td><td>

image

</td><td>

image

</td></table>

### CODE REVIEW

**Comment by XK9274** [comment]
Test process #1 complete on 215 - Looking like https://github.com/OnionUI/Onion/pull/973/commits/bc3f576f4f47eb8dfd2ca472314e13d1e728d16c has resolved directory issues.

**Comment by XK9274** [comment]
Confirmed fixed on formatted SD card & fresh build of branch on MMP 149
image

**Comment by XK9274** [comment]
Confirmed fixed on formatted SD card & fresh build of branch on MMP 217
image

**Comment by XK9274** [comment]
Added some functions to allow management of the shares instantly  - smbcontrol didn't end up being requiredas smbd is actively watching the config file (or appears to be, changes are instant)

- Need to find a home for:
`free(shares);`
If it's in the menu it causes problems due to how I've handled the action..... (maybe not the best way)



- When you go down into the Samba submenu, coming back up looks like you've also disabled the Master toggle for samba (it's aesthetic, smbd is still running)

**Comment by Aemiii91** [comment]
All done ✅

**Comment by DocMAX** [comment]
I have the latest beta on miyoo mini plus but no samba in "tweaks" menu

**Comment by tGecko** [comment]
The latest beta is not the same as the main branch, Samba will be included in the next beta realease.

**Pull request merged**
