### PR TITLE
SDL to framebuffer overlay + CPU clock hotkeys

### PR DESCRIPTION
**Pull request by tGecko**
SDL to framebuffer overlay + CPU clock hotkeys

### CODE REVIEW

**Review by Aemiii91 — APPROVED** [review]

**Comment by JordonVW** [comment]
Where is the cpuclock.txt file in Retroarch or is it integrated elsewhere now?

**Comment by Aemiii91** [comment]
@JordonVW no change since 4.2 (see [FAQ](https://onionui.github.io/docs/faq#how-to-overclock-my-miyoo-mini))

**Comment by JordonVW** [comment]
> @JordonVW no change since 4.2 (see [FAQ](https://onionui.github.io/docs/faq#how-to-overclock-my-miyoo-mini))

Ahh it seems when I updated to the latest beta it removes my overclock, I assumed the new overclock function was to set this value but it seems like it's a more on the fly type adjustment rather than saving the overclock you set.

**Comment by Aemiii91** [comment]
@JordonVW not sure why it got deleted (it shouldn't, afaik).. but yeah, this is just on-the-fly for now.

**Comment by JordonVW** [comment]
> @JordonVW not sure why it got deleted (it shouldn't, afaik).. but yeah, this is just on-the-fly for now.

It looks like this new overclock function overrides any overclock done with the old cpuclock.txt method in the retroarch folder and you have to use the new method on startup of each game.

**Comment by Aemiii91** [comment]
@JordonVW it does not affect the cpuclock.txt functionality at all. The cpuclock.txt is read and applied by RetroArch. The hotkeys will adjust the current clock speed (as reported by the hardware).

The combined flow is:
- `RetroArch/cpuclock.txt` is present with contents: "1500"
- RetroArch detects it and applies the clock speed value stated by the file
- the CPU clock is now at 1500
- pressing the OC hotkeys will either increase or decrease this value by 100
- exiting RetroArch will reset the clock speed

**Comment by JordonVW** [comment]
My mistake the file I made added an additional .txt ending to my file so it was cpuclock.txt.txt.

**Pull request merged**
