### PR TITLE
Dev v4.2 beta (#758) - Please add Polish language. My translation in attachment.

### PR DESCRIPTION
**Pull request by ghost**
Hi all ;)
Please add Polish language. I translated the whole thing :)
[pl.lang.zip](https://github.com/OnionUI/Onion/files/11464159/pl.lang.zip)

### CODE REVIEW

**Review by Aemiii91 — CHANGES_REQUESTED** [review]
Add the files to `static/build/miyoo/app/lang`

**Comment by Assassins78pl** [comment]
Uploads are disabled.
File uploads require push access to this repository.

**Comment by Assassins78pl** [comment]
:)

https://github.com/OnionUI/Onion/pull/827
https://github.com/OnionUI/Onion/pull/826

I'm doing it for the first time :)
I hope it is OK

**Comment by Aemiii91** [comment]
It works. You didn't have to split it into different PRs though 😅

**Pull request closed without merging**
