### PR TITLE
Added Turkish language support

### PR DESCRIPTION
**Pull request by tcgumus**
Hello,
I added Turkish language support.
Best regards,

### CODE REVIEW

**Comment by tcgumus** [comment]
hello
can i have some review @Aemiii91 :)
best regards

**Comment by Aemiii91** [comment]
Yes of course, I was just waiting until we were ready for releasing the beta.

**Review by Aemiii91 — APPROVED** [review]
Looks good!

**Comment by DukeNukemPL** [comment]
I added the files

en.lang.short
pl

Please check it's my first time here

love miyoo! bro

**Pull request merged**
